;;; packages.el -*- no-byte-compile: t; -*-

(package! ai-code :pin "024722baaf7249b666cf255ed11b2cf4f4235a04")
(package! ascii-art-to-unicode)
(package! chess)
(package! cider-eval-sexp-fu)
(package! clipmon)
(package! dashboard)
(package! edit-server)
(package! esup)
(package! eval-sexp-fu)
(package! feature-mode)
(package! highlight-sexp)
(package! ialign)
(package! k8s-mode)
(package! kubernetes)
(package! magit-todos)
(package! magit-delta)
(package! mise)
(package! monkeytype)
(package! nov)
(package! org-pomodoro)
(package! org-roam-ui)
(package! password-generator)
(package! powershell)
(package! pr-review :pin "938db766007f3444a2899b2457d9e2f4b4ffbebf")
(package! rainbow-delimiters)
(package! ultra-scroll)

(package! code-review :disable t)
(package! evil-snipe :disable t)
(package! flycheck-joker :disable t)

(when (featurep :system 'windows)
  (package! forge :disable t))
